permissions:
  contents: write
name: Build Rust project on multiple platforms when a new release is created

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, debian-latest, fedora-latest, alpine/latest]
        rust-version: [stable]

    env: 
      FILE_NAME: ${{ matrix.os }}-${{ github.event.release.tag_name }}.so
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}

      - name: Build project
        run: cargo build --release
      - name: rename file
        run: mv target/release/libnethsm_pkcs11.so ${{ env.FILE_NAME }}


      - name: Upload to the release
        uses: softprops/action-gh-release@v1
        with:
          file: ${{ env.FILE_NAME }}
